service:
  name: iot-message-lambda

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs8.10
  environment:
    # Tables defined by amplify
    HOST: ${file(../config.yml):host}

  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "iot:Publish"
      Resource:
        - ${file(../config.yml):arn}:topic/*

functions:
  iotMessageHandler:
      handler: functions/handler.iotMessageHandler
      events:
        - http:
            path: iotMessage/post
            method: post
            cors: true
  