service:
  name: iot-message-lambda

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs8.10
  environment:
    # Tables defined by amplify
    HOST: xxx.iot.us-east-1.amazonaws.com

  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "iot:Publish"
      Resource:
        - "arn:aws:iot:xxx:topic/*"

functions:
  iotMessageHandler:
      handler: functions/handler.iotMessageHandler
      events:
        - http:
            path: iotMessage/post
            method: post
            cors: true
  